name: bevel
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  get_it: ^7.2.0
  provider: ^6.0.2
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+3
  package_info_plus: ^1.4.2
  google_fonts: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.10
  injectable_generator: ^1.5.3
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true


