on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Run Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
     name: Run pub get
      - run: flutter pub get
     name: Run format lib
      - run: flutter format lib
      name: Run analyze
      - run: flutter analyze
      name: Run Test
      - run: flutter test
      name: Run diff
      - run: git diff
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs






# push to master, main, develop
# pull request on main master