on:

#  These events will trigger the work flow on the specified branches
# simply put: if u push or merge PR to either main or dev branches, these events will triger

  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev


name: "Quality Assurance"
jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter format lib
      - run: flutter analyze
      - run: flutter test
      - run: git diff
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --debug --split-per-abi

