on:

  #  These events will trigger the entire process.
  #  Any push or pull request merged to main or dev branch will trigger these process

  pull_request:
  push:
    branches:
      - main
      - dev

name: "Quality Assurance"
jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      name: Install dependencies
      run: flutter pub get
      name: Format lib folder
      run: flutter format lib
      name: Perform Analysis on Code
      run: flutter analyze
      name: Generate files
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      name: Track changes
      run: git diff
      name: Run test
      run: flutter test
