on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev


name: "Quality Assurance"
jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

        #For quality code assurance, these actions will be executed sequentially

        name: Instal Dependencies
      - run: flutter pub get

        name: format all file in the libe directory
      - run: flutter format lib

        name: Analyze Code, searching for problems and errors
      - run: flutter analyze

        name: Generate necessary files and delete conflicting files
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs

        name: Track changes made on a file
      - run: git diff

        name: Run test written in the test folder
      - run: flutter test


